/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Ballot__factory } from "./Ballot__factory";
export { SmartHealth__factory } from "./SmartHealth__factory";
